# Generated by Django 5.0.6 on 2024-10-19 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_company_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='clients',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField()),
                ('created_by', models.CharField(max_length=30)),
            ],
        ),
    ]
