# Generated by Django 5.0.6 on 2024-10-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_clients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='company',
            new_name='user',
        ),
    ]
