# Generated by Django 5.0.6 on 2024-10-19 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_rename_company_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('project_name', models.CharField(max_length=50)),
                ('Time_stand', models.DateField()),
            ],
        ),
    ]
